### PR TITLE
Pacs plabook folder

### PR DESCRIPTION
**Pull request by thiligh**
This is a Draft of the "What is a PACS Playbook"

I will add pictures for a visual description of some PACS devices. 

Will add links to each heading to allow quick access to a particular topic.

Will also provide information for the resources section.

### CODE REVIEW

**Review by bob-fontana — COMMENTED** [review]
Does anyone else think that an OCSP responder is a core component of a PACS Validation System?  I think it's part of the PKI Infrastructure.  Same as SCVP server.

A PACS Infrastructure Controller makes authorization decisions (i.e., who gets to go where when).  The Secure Controller is a 13.01 topology component that makes authentication decisions and notifies the PACS Infrastructure Controller of its decision on every card presented to a PIV Reader.

In a 13.02 topology, it's common to combine the PACS Infrastructure and Secure Controllers into a single piece of hardware.  The authentication has to be performed before the authorization decision can be acted upon.

For instance, one technique is to obtain an identifier from the card and determine whether access *will* be granted before even attempting authentication.  If access *will* be granted, the authentication is performed.  If not, access is denied before attempting authentication.  If authentication is successful, access is granted.  If authentication fails, access is denied.

So, the point here is that Authentication (AuthN) and Authorization (AuthZ) work hand-in-hand regardless of whether they are colocated on a single appliance.

**Comment by lachellel** [comment]
@bob-fontana 

agree

I haven't responded to this PR yet because we're just getting done with the push to Federalist for the first two.   I need to update the README on this repo to LIST all the target repositories, and better enumerate the eight subject areas and audiences. 

This repo (ficam-access) is holding the **FICAM Roadmap Part B** updates AND the FICAM artifacts from working groups - for access management _**policy and best practices for managing**_.  

The PACS content is a great start; needs some Plain Language scrubbing; and we have to move to a **different repo**.

**Comment by thiligh** [comment]
@bob-fontana  @lachellel 

Made updates to the draft "What is a PACS Playbook"

**Review by bob-fontana — COMMENTED** [review]
OCSP component clarification is good.

I know that this change doesn't cover it, but I'll be traveling and might not be able to comment for a day or two.  *All* types of controllers (Secure controllers, PACS Infrastructure controllers, door controllers) are inside the area being secured.  The only components allowed on the non-secure side are the reader components, i.e., card readers, LED displays, keypads, lights.  There is a distinct separation between reader and various controllers in order to prevent security-related decisions (including verification of challenge/response) from being made on the non-secure side.  This is all too technical for this article, but I wanted to give you a backdrop.

**Comment by lachellel** [comment]
@thiligh 

I'm going to close this Pull Request.  You're doing a lot of changes still ...and every change flows through into the PR so it's almost impossible to review! 

In addition, we will need to point this to another repo solely for the pacs plays.... but you'll be able to resubmit the PR!  don't worry...

**Pull request closed without merging**
